/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocol.dto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface HelloWorld {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"HelloWorld\",\"namespace\":\"protocol.dto\",\"types\":[{\"type\":\"record\",\"name\":\"Request\",\"fields\":[{\"name\":\"name\",\"type\":[\"string\",\"null\"]}]},{\"type\":\"enum\",\"name\":\"Status\",\"symbols\":[\"SYM1\",\"SYM2\"]},{\"type\":\"record\",\"name\":\"Response\",\"fields\":[{\"name\":\"nameToReturn\",\"type\":[\"string\",\"null\"]}]}],\"messages\":{\"send\":{\"request\":[{\"name\":\"request\",\"type\":\"Request\"},{\"name\":\"age\",\"type\":\"long\"},{\"name\":\"status\",\"type\":\"Status\"}],\"response\":\"Response\"}}}");
  /**
   */
  protocol.dto.Response send(protocol.dto.Request request, long age, protocol.dto.Status status) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends HelloWorld {
    public static final org.apache.avro.Protocol PROTOCOL = protocol.dto.HelloWorld.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void send(protocol.dto.Request request, long age, protocol.dto.Status status, org.apache.avro.ipc.Callback<protocol.dto.Response> callback) throws java.io.IOException;
  }
}