/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package protocol.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status {
  SYM1, SYM2  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"protocol.dto\",\"symbols\":[\"SYM1\",\"SYM2\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
