/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Flight extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3202221942852973152L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Flight\",\"namespace\":\"schema.dto\",\"fields\":[{\"name\":\"year\",\"type\":[\"int\",\"null\"]},{\"name\":\"month\",\"type\":[\"int\",\"null\"]},{\"name\":\"day_of_month\",\"type\":[\"int\",\"null\"]},{\"name\":\"day_of_week\",\"type\":[\"int\",\"null\"]},{\"name\":\"dep_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"crs_dep_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"arr_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"cs_arr_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"unique_carrier\",\"type\":[\"string\",\"null\"]},{\"name\":\"flight_num\",\"type\":[\"int\",\"null\"]},{\"name\":\"tail_num\",\"type\":[\"string\",\"null\"]},{\"name\":\"actual_elapsed_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"crs_elapsed_time\",\"type\":[\"int\",\"null\"]},{\"name\":\"air_time\",\"type\":[\"string\",\"null\"]},{\"name\":\"arr_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"dep_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"origin\",\"type\":[\"string\",\"null\"]},{\"name\":\"dest\",\"type\":[\"string\",\"null\"]},{\"name\":\"distance\",\"type\":[\"int\",\"null\"]},{\"name\":\"taxi_in\",\"type\":[\"string\",\"null\"]},{\"name\":\"taxi_out\",\"type\":[\"string\",\"null\"]},{\"name\":\"cancelled\",\"type\":[\"int\",\"null\"]},{\"name\":\"cancellation_code\",\"type\":[\"string\",\"null\"]},{\"name\":\"diverted\",\"type\":[\"int\",\"null\"]},{\"name\":\"carrier_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"weather_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"nas_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"security_delay\",\"type\":[\"string\",\"null\"]},{\"name\":\"late_aircraft_delay\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Flight> ENCODER =
      new BinaryMessageEncoder<Flight>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Flight> DECODER =
      new BinaryMessageDecoder<Flight>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Flight> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Flight> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Flight>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Flight to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Flight from a ByteBuffer. */
  public static Flight fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Integer year;
  @Deprecated public java.lang.Integer month;
  @Deprecated public java.lang.Integer day_of_month;
  @Deprecated public java.lang.Integer day_of_week;
  @Deprecated public java.lang.Integer dep_time;
  @Deprecated public java.lang.Integer crs_dep_time;
  @Deprecated public java.lang.Integer arr_time;
  @Deprecated public java.lang.Integer cs_arr_time;
  @Deprecated public java.lang.CharSequence unique_carrier;
  @Deprecated public java.lang.Integer flight_num;
  @Deprecated public java.lang.CharSequence tail_num;
  @Deprecated public java.lang.Integer actual_elapsed_time;
  @Deprecated public java.lang.Integer crs_elapsed_time;
  @Deprecated public java.lang.CharSequence air_time;
  @Deprecated public java.lang.CharSequence arr_delay;
  @Deprecated public java.lang.CharSequence dep_delay;
  @Deprecated public java.lang.CharSequence origin;
  @Deprecated public java.lang.CharSequence dest;
  @Deprecated public java.lang.Integer distance;
  @Deprecated public java.lang.CharSequence taxi_in;
  @Deprecated public java.lang.CharSequence taxi_out;
  @Deprecated public java.lang.Integer cancelled;
  @Deprecated public java.lang.CharSequence cancellation_code;
  @Deprecated public java.lang.Integer diverted;
  @Deprecated public java.lang.CharSequence carrier_delay;
  @Deprecated public java.lang.CharSequence weather_delay;
  @Deprecated public java.lang.CharSequence nas_delay;
  @Deprecated public java.lang.CharSequence security_delay;
  @Deprecated public java.lang.CharSequence late_aircraft_delay;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Flight() {}

  /**
   * All-args constructor.
   * @param year The new value for year
   * @param month The new value for month
   * @param day_of_month The new value for day_of_month
   * @param day_of_week The new value for day_of_week
   * @param dep_time The new value for dep_time
   * @param crs_dep_time The new value for crs_dep_time
   * @param arr_time The new value for arr_time
   * @param cs_arr_time The new value for cs_arr_time
   * @param unique_carrier The new value for unique_carrier
   * @param flight_num The new value for flight_num
   * @param tail_num The new value for tail_num
   * @param actual_elapsed_time The new value for actual_elapsed_time
   * @param crs_elapsed_time The new value for crs_elapsed_time
   * @param air_time The new value for air_time
   * @param arr_delay The new value for arr_delay
   * @param dep_delay The new value for dep_delay
   * @param origin The new value for origin
   * @param dest The new value for dest
   * @param distance The new value for distance
   * @param taxi_in The new value for taxi_in
   * @param taxi_out The new value for taxi_out
   * @param cancelled The new value for cancelled
   * @param cancellation_code The new value for cancellation_code
   * @param diverted The new value for diverted
   * @param carrier_delay The new value for carrier_delay
   * @param weather_delay The new value for weather_delay
   * @param nas_delay The new value for nas_delay
   * @param security_delay The new value for security_delay
   * @param late_aircraft_delay The new value for late_aircraft_delay
   */
  public Flight(java.lang.Integer year, java.lang.Integer month, java.lang.Integer day_of_month, java.lang.Integer day_of_week, java.lang.Integer dep_time, java.lang.Integer crs_dep_time, java.lang.Integer arr_time, java.lang.Integer cs_arr_time, java.lang.CharSequence unique_carrier, java.lang.Integer flight_num, java.lang.CharSequence tail_num, java.lang.Integer actual_elapsed_time, java.lang.Integer crs_elapsed_time, java.lang.CharSequence air_time, java.lang.CharSequence arr_delay, java.lang.CharSequence dep_delay, java.lang.CharSequence origin, java.lang.CharSequence dest, java.lang.Integer distance, java.lang.CharSequence taxi_in, java.lang.CharSequence taxi_out, java.lang.Integer cancelled, java.lang.CharSequence cancellation_code, java.lang.Integer diverted, java.lang.CharSequence carrier_delay, java.lang.CharSequence weather_delay, java.lang.CharSequence nas_delay, java.lang.CharSequence security_delay, java.lang.CharSequence late_aircraft_delay) {
    this.year = year;
    this.month = month;
    this.day_of_month = day_of_month;
    this.day_of_week = day_of_week;
    this.dep_time = dep_time;
    this.crs_dep_time = crs_dep_time;
    this.arr_time = arr_time;
    this.cs_arr_time = cs_arr_time;
    this.unique_carrier = unique_carrier;
    this.flight_num = flight_num;
    this.tail_num = tail_num;
    this.actual_elapsed_time = actual_elapsed_time;
    this.crs_elapsed_time = crs_elapsed_time;
    this.air_time = air_time;
    this.arr_delay = arr_delay;
    this.dep_delay = dep_delay;
    this.origin = origin;
    this.dest = dest;
    this.distance = distance;
    this.taxi_in = taxi_in;
    this.taxi_out = taxi_out;
    this.cancelled = cancelled;
    this.cancellation_code = cancellation_code;
    this.diverted = diverted;
    this.carrier_delay = carrier_delay;
    this.weather_delay = weather_delay;
    this.nas_delay = nas_delay;
    this.security_delay = security_delay;
    this.late_aircraft_delay = late_aircraft_delay;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return year;
    case 1: return month;
    case 2: return day_of_month;
    case 3: return day_of_week;
    case 4: return dep_time;
    case 5: return crs_dep_time;
    case 6: return arr_time;
    case 7: return cs_arr_time;
    case 8: return unique_carrier;
    case 9: return flight_num;
    case 10: return tail_num;
    case 11: return actual_elapsed_time;
    case 12: return crs_elapsed_time;
    case 13: return air_time;
    case 14: return arr_delay;
    case 15: return dep_delay;
    case 16: return origin;
    case 17: return dest;
    case 18: return distance;
    case 19: return taxi_in;
    case 20: return taxi_out;
    case 21: return cancelled;
    case 22: return cancellation_code;
    case 23: return diverted;
    case 24: return carrier_delay;
    case 25: return weather_delay;
    case 26: return nas_delay;
    case 27: return security_delay;
    case 28: return late_aircraft_delay;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: year = (java.lang.Integer)value$; break;
    case 1: month = (java.lang.Integer)value$; break;
    case 2: day_of_month = (java.lang.Integer)value$; break;
    case 3: day_of_week = (java.lang.Integer)value$; break;
    case 4: dep_time = (java.lang.Integer)value$; break;
    case 5: crs_dep_time = (java.lang.Integer)value$; break;
    case 6: arr_time = (java.lang.Integer)value$; break;
    case 7: cs_arr_time = (java.lang.Integer)value$; break;
    case 8: unique_carrier = (java.lang.CharSequence)value$; break;
    case 9: flight_num = (java.lang.Integer)value$; break;
    case 10: tail_num = (java.lang.CharSequence)value$; break;
    case 11: actual_elapsed_time = (java.lang.Integer)value$; break;
    case 12: crs_elapsed_time = (java.lang.Integer)value$; break;
    case 13: air_time = (java.lang.CharSequence)value$; break;
    case 14: arr_delay = (java.lang.CharSequence)value$; break;
    case 15: dep_delay = (java.lang.CharSequence)value$; break;
    case 16: origin = (java.lang.CharSequence)value$; break;
    case 17: dest = (java.lang.CharSequence)value$; break;
    case 18: distance = (java.lang.Integer)value$; break;
    case 19: taxi_in = (java.lang.CharSequence)value$; break;
    case 20: taxi_out = (java.lang.CharSequence)value$; break;
    case 21: cancelled = (java.lang.Integer)value$; break;
    case 22: cancellation_code = (java.lang.CharSequence)value$; break;
    case 23: diverted = (java.lang.Integer)value$; break;
    case 24: carrier_delay = (java.lang.CharSequence)value$; break;
    case 25: weather_delay = (java.lang.CharSequence)value$; break;
    case 26: nas_delay = (java.lang.CharSequence)value$; break;
    case 27: security_delay = (java.lang.CharSequence)value$; break;
    case 28: late_aircraft_delay = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'year' field.
   * @return The value of the 'year' field.
   */
  public java.lang.Integer getYear() {
    return year;
  }

  /**
   * Sets the value of the 'year' field.
   * @param value the value to set.
   */
  public void setYear(java.lang.Integer value) {
    this.year = value;
  }

  /**
   * Gets the value of the 'month' field.
   * @return The value of the 'month' field.
   */
  public java.lang.Integer getMonth() {
    return month;
  }

  /**
   * Sets the value of the 'month' field.
   * @param value the value to set.
   */
  public void setMonth(java.lang.Integer value) {
    this.month = value;
  }

  /**
   * Gets the value of the 'day_of_month' field.
   * @return The value of the 'day_of_month' field.
   */
  public java.lang.Integer getDayOfMonth() {
    return day_of_month;
  }

  /**
   * Sets the value of the 'day_of_month' field.
   * @param value the value to set.
   */
  public void setDayOfMonth(java.lang.Integer value) {
    this.day_of_month = value;
  }

  /**
   * Gets the value of the 'day_of_week' field.
   * @return The value of the 'day_of_week' field.
   */
  public java.lang.Integer getDayOfWeek() {
    return day_of_week;
  }

  /**
   * Sets the value of the 'day_of_week' field.
   * @param value the value to set.
   */
  public void setDayOfWeek(java.lang.Integer value) {
    this.day_of_week = value;
  }

  /**
   * Gets the value of the 'dep_time' field.
   * @return The value of the 'dep_time' field.
   */
  public java.lang.Integer getDepTime() {
    return dep_time;
  }

  /**
   * Sets the value of the 'dep_time' field.
   * @param value the value to set.
   */
  public void setDepTime(java.lang.Integer value) {
    this.dep_time = value;
  }

  /**
   * Gets the value of the 'crs_dep_time' field.
   * @return The value of the 'crs_dep_time' field.
   */
  public java.lang.Integer getCrsDepTime() {
    return crs_dep_time;
  }

  /**
   * Sets the value of the 'crs_dep_time' field.
   * @param value the value to set.
   */
  public void setCrsDepTime(java.lang.Integer value) {
    this.crs_dep_time = value;
  }

  /**
   * Gets the value of the 'arr_time' field.
   * @return The value of the 'arr_time' field.
   */
  public java.lang.Integer getArrTime() {
    return arr_time;
  }

  /**
   * Sets the value of the 'arr_time' field.
   * @param value the value to set.
   */
  public void setArrTime(java.lang.Integer value) {
    this.arr_time = value;
  }

  /**
   * Gets the value of the 'cs_arr_time' field.
   * @return The value of the 'cs_arr_time' field.
   */
  public java.lang.Integer getCsArrTime() {
    return cs_arr_time;
  }

  /**
   * Sets the value of the 'cs_arr_time' field.
   * @param value the value to set.
   */
  public void setCsArrTime(java.lang.Integer value) {
    this.cs_arr_time = value;
  }

  /**
   * Gets the value of the 'unique_carrier' field.
   * @return The value of the 'unique_carrier' field.
   */
  public java.lang.CharSequence getUniqueCarrier() {
    return unique_carrier;
  }

  /**
   * Sets the value of the 'unique_carrier' field.
   * @param value the value to set.
   */
  public void setUniqueCarrier(java.lang.CharSequence value) {
    this.unique_carrier = value;
  }

  /**
   * Gets the value of the 'flight_num' field.
   * @return The value of the 'flight_num' field.
   */
  public java.lang.Integer getFlightNum() {
    return flight_num;
  }

  /**
   * Sets the value of the 'flight_num' field.
   * @param value the value to set.
   */
  public void setFlightNum(java.lang.Integer value) {
    this.flight_num = value;
  }

  /**
   * Gets the value of the 'tail_num' field.
   * @return The value of the 'tail_num' field.
   */
  public java.lang.CharSequence getTailNum() {
    return tail_num;
  }

  /**
   * Sets the value of the 'tail_num' field.
   * @param value the value to set.
   */
  public void setTailNum(java.lang.CharSequence value) {
    this.tail_num = value;
  }

  /**
   * Gets the value of the 'actual_elapsed_time' field.
   * @return The value of the 'actual_elapsed_time' field.
   */
  public java.lang.Integer getActualElapsedTime() {
    return actual_elapsed_time;
  }

  /**
   * Sets the value of the 'actual_elapsed_time' field.
   * @param value the value to set.
   */
  public void setActualElapsedTime(java.lang.Integer value) {
    this.actual_elapsed_time = value;
  }

  /**
   * Gets the value of the 'crs_elapsed_time' field.
   * @return The value of the 'crs_elapsed_time' field.
   */
  public java.lang.Integer getCrsElapsedTime() {
    return crs_elapsed_time;
  }

  /**
   * Sets the value of the 'crs_elapsed_time' field.
   * @param value the value to set.
   */
  public void setCrsElapsedTime(java.lang.Integer value) {
    this.crs_elapsed_time = value;
  }

  /**
   * Gets the value of the 'air_time' field.
   * @return The value of the 'air_time' field.
   */
  public java.lang.CharSequence getAirTime() {
    return air_time;
  }

  /**
   * Sets the value of the 'air_time' field.
   * @param value the value to set.
   */
  public void setAirTime(java.lang.CharSequence value) {
    this.air_time = value;
  }

  /**
   * Gets the value of the 'arr_delay' field.
   * @return The value of the 'arr_delay' field.
   */
  public java.lang.CharSequence getArrDelay() {
    return arr_delay;
  }

  /**
   * Sets the value of the 'arr_delay' field.
   * @param value the value to set.
   */
  public void setArrDelay(java.lang.CharSequence value) {
    this.arr_delay = value;
  }

  /**
   * Gets the value of the 'dep_delay' field.
   * @return The value of the 'dep_delay' field.
   */
  public java.lang.CharSequence getDepDelay() {
    return dep_delay;
  }

  /**
   * Sets the value of the 'dep_delay' field.
   * @param value the value to set.
   */
  public void setDepDelay(java.lang.CharSequence value) {
    this.dep_delay = value;
  }

  /**
   * Gets the value of the 'origin' field.
   * @return The value of the 'origin' field.
   */
  public java.lang.CharSequence getOrigin() {
    return origin;
  }

  /**
   * Sets the value of the 'origin' field.
   * @param value the value to set.
   */
  public void setOrigin(java.lang.CharSequence value) {
    this.origin = value;
  }

  /**
   * Gets the value of the 'dest' field.
   * @return The value of the 'dest' field.
   */
  public java.lang.CharSequence getDest() {
    return dest;
  }

  /**
   * Sets the value of the 'dest' field.
   * @param value the value to set.
   */
  public void setDest(java.lang.CharSequence value) {
    this.dest = value;
  }

  /**
   * Gets the value of the 'distance' field.
   * @return The value of the 'distance' field.
   */
  public java.lang.Integer getDistance() {
    return distance;
  }

  /**
   * Sets the value of the 'distance' field.
   * @param value the value to set.
   */
  public void setDistance(java.lang.Integer value) {
    this.distance = value;
  }

  /**
   * Gets the value of the 'taxi_in' field.
   * @return The value of the 'taxi_in' field.
   */
  public java.lang.CharSequence getTaxiIn() {
    return taxi_in;
  }

  /**
   * Sets the value of the 'taxi_in' field.
   * @param value the value to set.
   */
  public void setTaxiIn(java.lang.CharSequence value) {
    this.taxi_in = value;
  }

  /**
   * Gets the value of the 'taxi_out' field.
   * @return The value of the 'taxi_out' field.
   */
  public java.lang.CharSequence getTaxiOut() {
    return taxi_out;
  }

  /**
   * Sets the value of the 'taxi_out' field.
   * @param value the value to set.
   */
  public void setTaxiOut(java.lang.CharSequence value) {
    this.taxi_out = value;
  }

  /**
   * Gets the value of the 'cancelled' field.
   * @return The value of the 'cancelled' field.
   */
  public java.lang.Integer getCancelled() {
    return cancelled;
  }

  /**
   * Sets the value of the 'cancelled' field.
   * @param value the value to set.
   */
  public void setCancelled(java.lang.Integer value) {
    this.cancelled = value;
  }

  /**
   * Gets the value of the 'cancellation_code' field.
   * @return The value of the 'cancellation_code' field.
   */
  public java.lang.CharSequence getCancellationCode() {
    return cancellation_code;
  }

  /**
   * Sets the value of the 'cancellation_code' field.
   * @param value the value to set.
   */
  public void setCancellationCode(java.lang.CharSequence value) {
    this.cancellation_code = value;
  }

  /**
   * Gets the value of the 'diverted' field.
   * @return The value of the 'diverted' field.
   */
  public java.lang.Integer getDiverted() {
    return diverted;
  }

  /**
   * Sets the value of the 'diverted' field.
   * @param value the value to set.
   */
  public void setDiverted(java.lang.Integer value) {
    this.diverted = value;
  }

  /**
   * Gets the value of the 'carrier_delay' field.
   * @return The value of the 'carrier_delay' field.
   */
  public java.lang.CharSequence getCarrierDelay() {
    return carrier_delay;
  }

  /**
   * Sets the value of the 'carrier_delay' field.
   * @param value the value to set.
   */
  public void setCarrierDelay(java.lang.CharSequence value) {
    this.carrier_delay = value;
  }

  /**
   * Gets the value of the 'weather_delay' field.
   * @return The value of the 'weather_delay' field.
   */
  public java.lang.CharSequence getWeatherDelay() {
    return weather_delay;
  }

  /**
   * Sets the value of the 'weather_delay' field.
   * @param value the value to set.
   */
  public void setWeatherDelay(java.lang.CharSequence value) {
    this.weather_delay = value;
  }

  /**
   * Gets the value of the 'nas_delay' field.
   * @return The value of the 'nas_delay' field.
   */
  public java.lang.CharSequence getNasDelay() {
    return nas_delay;
  }

  /**
   * Sets the value of the 'nas_delay' field.
   * @param value the value to set.
   */
  public void setNasDelay(java.lang.CharSequence value) {
    this.nas_delay = value;
  }

  /**
   * Gets the value of the 'security_delay' field.
   * @return The value of the 'security_delay' field.
   */
  public java.lang.CharSequence getSecurityDelay() {
    return security_delay;
  }

  /**
   * Sets the value of the 'security_delay' field.
   * @param value the value to set.
   */
  public void setSecurityDelay(java.lang.CharSequence value) {
    this.security_delay = value;
  }

  /**
   * Gets the value of the 'late_aircraft_delay' field.
   * @return The value of the 'late_aircraft_delay' field.
   */
  public java.lang.CharSequence getLateAircraftDelay() {
    return late_aircraft_delay;
  }

  /**
   * Sets the value of the 'late_aircraft_delay' field.
   * @param value the value to set.
   */
  public void setLateAircraftDelay(java.lang.CharSequence value) {
    this.late_aircraft_delay = value;
  }

  /**
   * Creates a new Flight RecordBuilder.
   * @return A new Flight RecordBuilder
   */
  public static schema.dto.Flight.Builder newBuilder() {
    return new schema.dto.Flight.Builder();
  }

  /**
   * Creates a new Flight RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Flight RecordBuilder
   */
  public static schema.dto.Flight.Builder newBuilder(schema.dto.Flight.Builder other) {
    return new schema.dto.Flight.Builder(other);
  }

  /**
   * Creates a new Flight RecordBuilder by copying an existing Flight instance.
   * @param other The existing instance to copy.
   * @return A new Flight RecordBuilder
   */
  public static schema.dto.Flight.Builder newBuilder(schema.dto.Flight other) {
    return new schema.dto.Flight.Builder(other);
  }

  /**
   * RecordBuilder for Flight instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Flight>
    implements org.apache.avro.data.RecordBuilder<Flight> {

    private java.lang.Integer year;
    private java.lang.Integer month;
    private java.lang.Integer day_of_month;
    private java.lang.Integer day_of_week;
    private java.lang.Integer dep_time;
    private java.lang.Integer crs_dep_time;
    private java.lang.Integer arr_time;
    private java.lang.Integer cs_arr_time;
    private java.lang.CharSequence unique_carrier;
    private java.lang.Integer flight_num;
    private java.lang.CharSequence tail_num;
    private java.lang.Integer actual_elapsed_time;
    private java.lang.Integer crs_elapsed_time;
    private java.lang.CharSequence air_time;
    private java.lang.CharSequence arr_delay;
    private java.lang.CharSequence dep_delay;
    private java.lang.CharSequence origin;
    private java.lang.CharSequence dest;
    private java.lang.Integer distance;
    private java.lang.CharSequence taxi_in;
    private java.lang.CharSequence taxi_out;
    private java.lang.Integer cancelled;
    private java.lang.CharSequence cancellation_code;
    private java.lang.Integer diverted;
    private java.lang.CharSequence carrier_delay;
    private java.lang.CharSequence weather_delay;
    private java.lang.CharSequence nas_delay;
    private java.lang.CharSequence security_delay;
    private java.lang.CharSequence late_aircraft_delay;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schema.dto.Flight.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.year)) {
        this.year = data().deepCopy(fields()[0].schema(), other.year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.month)) {
        this.month = data().deepCopy(fields()[1].schema(), other.month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.day_of_month)) {
        this.day_of_month = data().deepCopy(fields()[2].schema(), other.day_of_month);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.day_of_week)) {
        this.day_of_week = data().deepCopy(fields()[3].schema(), other.day_of_week);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.dep_time)) {
        this.dep_time = data().deepCopy(fields()[4].schema(), other.dep_time);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.crs_dep_time)) {
        this.crs_dep_time = data().deepCopy(fields()[5].schema(), other.crs_dep_time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.arr_time)) {
        this.arr_time = data().deepCopy(fields()[6].schema(), other.arr_time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cs_arr_time)) {
        this.cs_arr_time = data().deepCopy(fields()[7].schema(), other.cs_arr_time);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.unique_carrier)) {
        this.unique_carrier = data().deepCopy(fields()[8].schema(), other.unique_carrier);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.flight_num)) {
        this.flight_num = data().deepCopy(fields()[9].schema(), other.flight_num);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tail_num)) {
        this.tail_num = data().deepCopy(fields()[10].schema(), other.tail_num);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.actual_elapsed_time)) {
        this.actual_elapsed_time = data().deepCopy(fields()[11].schema(), other.actual_elapsed_time);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.crs_elapsed_time)) {
        this.crs_elapsed_time = data().deepCopy(fields()[12].schema(), other.crs_elapsed_time);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.air_time)) {
        this.air_time = data().deepCopy(fields()[13].schema(), other.air_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.arr_delay)) {
        this.arr_delay = data().deepCopy(fields()[14].schema(), other.arr_delay);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.dep_delay)) {
        this.dep_delay = data().deepCopy(fields()[15].schema(), other.dep_delay);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.origin)) {
        this.origin = data().deepCopy(fields()[16].schema(), other.origin);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.dest)) {
        this.dest = data().deepCopy(fields()[17].schema(), other.dest);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.distance)) {
        this.distance = data().deepCopy(fields()[18].schema(), other.distance);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.taxi_in)) {
        this.taxi_in = data().deepCopy(fields()[19].schema(), other.taxi_in);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.taxi_out)) {
        this.taxi_out = data().deepCopy(fields()[20].schema(), other.taxi_out);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.cancelled)) {
        this.cancelled = data().deepCopy(fields()[21].schema(), other.cancelled);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.cancellation_code)) {
        this.cancellation_code = data().deepCopy(fields()[22].schema(), other.cancellation_code);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.diverted)) {
        this.diverted = data().deepCopy(fields()[23].schema(), other.diverted);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.carrier_delay)) {
        this.carrier_delay = data().deepCopy(fields()[24].schema(), other.carrier_delay);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.weather_delay)) {
        this.weather_delay = data().deepCopy(fields()[25].schema(), other.weather_delay);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.nas_delay)) {
        this.nas_delay = data().deepCopy(fields()[26].schema(), other.nas_delay);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.security_delay)) {
        this.security_delay = data().deepCopy(fields()[27].schema(), other.security_delay);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.late_aircraft_delay)) {
        this.late_aircraft_delay = data().deepCopy(fields()[28].schema(), other.late_aircraft_delay);
        fieldSetFlags()[28] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Flight instance
     * @param other The existing instance to copy.
     */
    private Builder(schema.dto.Flight other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.year)) {
        this.year = data().deepCopy(fields()[0].schema(), other.year);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.month)) {
        this.month = data().deepCopy(fields()[1].schema(), other.month);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.day_of_month)) {
        this.day_of_month = data().deepCopy(fields()[2].schema(), other.day_of_month);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.day_of_week)) {
        this.day_of_week = data().deepCopy(fields()[3].schema(), other.day_of_week);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.dep_time)) {
        this.dep_time = data().deepCopy(fields()[4].schema(), other.dep_time);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.crs_dep_time)) {
        this.crs_dep_time = data().deepCopy(fields()[5].schema(), other.crs_dep_time);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.arr_time)) {
        this.arr_time = data().deepCopy(fields()[6].schema(), other.arr_time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.cs_arr_time)) {
        this.cs_arr_time = data().deepCopy(fields()[7].schema(), other.cs_arr_time);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.unique_carrier)) {
        this.unique_carrier = data().deepCopy(fields()[8].schema(), other.unique_carrier);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.flight_num)) {
        this.flight_num = data().deepCopy(fields()[9].schema(), other.flight_num);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tail_num)) {
        this.tail_num = data().deepCopy(fields()[10].schema(), other.tail_num);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.actual_elapsed_time)) {
        this.actual_elapsed_time = data().deepCopy(fields()[11].schema(), other.actual_elapsed_time);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.crs_elapsed_time)) {
        this.crs_elapsed_time = data().deepCopy(fields()[12].schema(), other.crs_elapsed_time);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.air_time)) {
        this.air_time = data().deepCopy(fields()[13].schema(), other.air_time);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.arr_delay)) {
        this.arr_delay = data().deepCopy(fields()[14].schema(), other.arr_delay);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.dep_delay)) {
        this.dep_delay = data().deepCopy(fields()[15].schema(), other.dep_delay);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.origin)) {
        this.origin = data().deepCopy(fields()[16].schema(), other.origin);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.dest)) {
        this.dest = data().deepCopy(fields()[17].schema(), other.dest);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.distance)) {
        this.distance = data().deepCopy(fields()[18].schema(), other.distance);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.taxi_in)) {
        this.taxi_in = data().deepCopy(fields()[19].schema(), other.taxi_in);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.taxi_out)) {
        this.taxi_out = data().deepCopy(fields()[20].schema(), other.taxi_out);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.cancelled)) {
        this.cancelled = data().deepCopy(fields()[21].schema(), other.cancelled);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.cancellation_code)) {
        this.cancellation_code = data().deepCopy(fields()[22].schema(), other.cancellation_code);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.diverted)) {
        this.diverted = data().deepCopy(fields()[23].schema(), other.diverted);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.carrier_delay)) {
        this.carrier_delay = data().deepCopy(fields()[24].schema(), other.carrier_delay);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.weather_delay)) {
        this.weather_delay = data().deepCopy(fields()[25].schema(), other.weather_delay);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.nas_delay)) {
        this.nas_delay = data().deepCopy(fields()[26].schema(), other.nas_delay);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.security_delay)) {
        this.security_delay = data().deepCopy(fields()[27].schema(), other.security_delay);
        fieldSetFlags()[27] = true;
      }
      if (isValidValue(fields()[28], other.late_aircraft_delay)) {
        this.late_aircraft_delay = data().deepCopy(fields()[28].schema(), other.late_aircraft_delay);
        fieldSetFlags()[28] = true;
      }
    }

    /**
      * Gets the value of the 'year' field.
      * @return The value.
      */
    public java.lang.Integer getYear() {
      return year;
    }

    /**
      * Sets the value of the 'year' field.
      * @param value The value of 'year'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setYear(java.lang.Integer value) {
      validate(fields()[0], value);
      this.year = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'year' field has been set.
      * @return True if the 'year' field has been set, false otherwise.
      */
    public boolean hasYear() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'year' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearYear() {
      year = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'month' field.
      * @return The value.
      */
    public java.lang.Integer getMonth() {
      return month;
    }

    /**
      * Sets the value of the 'month' field.
      * @param value The value of 'month'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setMonth(java.lang.Integer value) {
      validate(fields()[1], value);
      this.month = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'month' field has been set.
      * @return True if the 'month' field has been set, false otherwise.
      */
    public boolean hasMonth() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'month' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearMonth() {
      month = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'day_of_month' field.
      * @return The value.
      */
    public java.lang.Integer getDayOfMonth() {
      return day_of_month;
    }

    /**
      * Sets the value of the 'day_of_month' field.
      * @param value The value of 'day_of_month'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDayOfMonth(java.lang.Integer value) {
      validate(fields()[2], value);
      this.day_of_month = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'day_of_month' field has been set.
      * @return True if the 'day_of_month' field has been set, false otherwise.
      */
    public boolean hasDayOfMonth() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'day_of_month' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDayOfMonth() {
      day_of_month = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'day_of_week' field.
      * @return The value.
      */
    public java.lang.Integer getDayOfWeek() {
      return day_of_week;
    }

    /**
      * Sets the value of the 'day_of_week' field.
      * @param value The value of 'day_of_week'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDayOfWeek(java.lang.Integer value) {
      validate(fields()[3], value);
      this.day_of_week = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'day_of_week' field has been set.
      * @return True if the 'day_of_week' field has been set, false otherwise.
      */
    public boolean hasDayOfWeek() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'day_of_week' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDayOfWeek() {
      day_of_week = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'dep_time' field.
      * @return The value.
      */
    public java.lang.Integer getDepTime() {
      return dep_time;
    }

    /**
      * Sets the value of the 'dep_time' field.
      * @param value The value of 'dep_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDepTime(java.lang.Integer value) {
      validate(fields()[4], value);
      this.dep_time = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'dep_time' field has been set.
      * @return True if the 'dep_time' field has been set, false otherwise.
      */
    public boolean hasDepTime() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'dep_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDepTime() {
      dep_time = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'crs_dep_time' field.
      * @return The value.
      */
    public java.lang.Integer getCrsDepTime() {
      return crs_dep_time;
    }

    /**
      * Sets the value of the 'crs_dep_time' field.
      * @param value The value of 'crs_dep_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCrsDepTime(java.lang.Integer value) {
      validate(fields()[5], value);
      this.crs_dep_time = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'crs_dep_time' field has been set.
      * @return True if the 'crs_dep_time' field has been set, false otherwise.
      */
    public boolean hasCrsDepTime() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'crs_dep_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCrsDepTime() {
      crs_dep_time = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'arr_time' field.
      * @return The value.
      */
    public java.lang.Integer getArrTime() {
      return arr_time;
    }

    /**
      * Sets the value of the 'arr_time' field.
      * @param value The value of 'arr_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setArrTime(java.lang.Integer value) {
      validate(fields()[6], value);
      this.arr_time = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'arr_time' field has been set.
      * @return True if the 'arr_time' field has been set, false otherwise.
      */
    public boolean hasArrTime() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'arr_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearArrTime() {
      arr_time = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'cs_arr_time' field.
      * @return The value.
      */
    public java.lang.Integer getCsArrTime() {
      return cs_arr_time;
    }

    /**
      * Sets the value of the 'cs_arr_time' field.
      * @param value The value of 'cs_arr_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCsArrTime(java.lang.Integer value) {
      validate(fields()[7], value);
      this.cs_arr_time = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'cs_arr_time' field has been set.
      * @return True if the 'cs_arr_time' field has been set, false otherwise.
      */
    public boolean hasCsArrTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'cs_arr_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCsArrTime() {
      cs_arr_time = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'unique_carrier' field.
      * @return The value.
      */
    public java.lang.CharSequence getUniqueCarrier() {
      return unique_carrier;
    }

    /**
      * Sets the value of the 'unique_carrier' field.
      * @param value The value of 'unique_carrier'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setUniqueCarrier(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.unique_carrier = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'unique_carrier' field has been set.
      * @return True if the 'unique_carrier' field has been set, false otherwise.
      */
    public boolean hasUniqueCarrier() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'unique_carrier' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearUniqueCarrier() {
      unique_carrier = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'flight_num' field.
      * @return The value.
      */
    public java.lang.Integer getFlightNum() {
      return flight_num;
    }

    /**
      * Sets the value of the 'flight_num' field.
      * @param value The value of 'flight_num'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setFlightNum(java.lang.Integer value) {
      validate(fields()[9], value);
      this.flight_num = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'flight_num' field has been set.
      * @return True if the 'flight_num' field has been set, false otherwise.
      */
    public boolean hasFlightNum() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'flight_num' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearFlightNum() {
      flight_num = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'tail_num' field.
      * @return The value.
      */
    public java.lang.CharSequence getTailNum() {
      return tail_num;
    }

    /**
      * Sets the value of the 'tail_num' field.
      * @param value The value of 'tail_num'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setTailNum(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.tail_num = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'tail_num' field has been set.
      * @return True if the 'tail_num' field has been set, false otherwise.
      */
    public boolean hasTailNum() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'tail_num' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearTailNum() {
      tail_num = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'actual_elapsed_time' field.
      * @return The value.
      */
    public java.lang.Integer getActualElapsedTime() {
      return actual_elapsed_time;
    }

    /**
      * Sets the value of the 'actual_elapsed_time' field.
      * @param value The value of 'actual_elapsed_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setActualElapsedTime(java.lang.Integer value) {
      validate(fields()[11], value);
      this.actual_elapsed_time = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'actual_elapsed_time' field has been set.
      * @return True if the 'actual_elapsed_time' field has been set, false otherwise.
      */
    public boolean hasActualElapsedTime() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'actual_elapsed_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearActualElapsedTime() {
      actual_elapsed_time = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'crs_elapsed_time' field.
      * @return The value.
      */
    public java.lang.Integer getCrsElapsedTime() {
      return crs_elapsed_time;
    }

    /**
      * Sets the value of the 'crs_elapsed_time' field.
      * @param value The value of 'crs_elapsed_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCrsElapsedTime(java.lang.Integer value) {
      validate(fields()[12], value);
      this.crs_elapsed_time = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'crs_elapsed_time' field has been set.
      * @return True if the 'crs_elapsed_time' field has been set, false otherwise.
      */
    public boolean hasCrsElapsedTime() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'crs_elapsed_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCrsElapsedTime() {
      crs_elapsed_time = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'air_time' field.
      * @return The value.
      */
    public java.lang.CharSequence getAirTime() {
      return air_time;
    }

    /**
      * Sets the value of the 'air_time' field.
      * @param value The value of 'air_time'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setAirTime(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.air_time = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'air_time' field has been set.
      * @return True if the 'air_time' field has been set, false otherwise.
      */
    public boolean hasAirTime() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'air_time' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearAirTime() {
      air_time = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'arr_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getArrDelay() {
      return arr_delay;
    }

    /**
      * Sets the value of the 'arr_delay' field.
      * @param value The value of 'arr_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setArrDelay(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.arr_delay = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'arr_delay' field has been set.
      * @return True if the 'arr_delay' field has been set, false otherwise.
      */
    public boolean hasArrDelay() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'arr_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearArrDelay() {
      arr_delay = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'dep_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepDelay() {
      return dep_delay;
    }

    /**
      * Sets the value of the 'dep_delay' field.
      * @param value The value of 'dep_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDepDelay(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.dep_delay = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'dep_delay' field has been set.
      * @return True if the 'dep_delay' field has been set, false otherwise.
      */
    public boolean hasDepDelay() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'dep_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDepDelay() {
      dep_delay = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'origin' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrigin() {
      return origin;
    }

    /**
      * Sets the value of the 'origin' field.
      * @param value The value of 'origin'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setOrigin(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.origin = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'origin' field has been set.
      * @return True if the 'origin' field has been set, false otherwise.
      */
    public boolean hasOrigin() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'origin' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearOrigin() {
      origin = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'dest' field.
      * @return The value.
      */
    public java.lang.CharSequence getDest() {
      return dest;
    }

    /**
      * Sets the value of the 'dest' field.
      * @param value The value of 'dest'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDest(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.dest = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'dest' field has been set.
      * @return True if the 'dest' field has been set, false otherwise.
      */
    public boolean hasDest() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'dest' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDest() {
      dest = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'distance' field.
      * @return The value.
      */
    public java.lang.Integer getDistance() {
      return distance;
    }

    /**
      * Sets the value of the 'distance' field.
      * @param value The value of 'distance'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDistance(java.lang.Integer value) {
      validate(fields()[18], value);
      this.distance = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'distance' field has been set.
      * @return True if the 'distance' field has been set, false otherwise.
      */
    public boolean hasDistance() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'distance' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDistance() {
      distance = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'taxi_in' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaxiIn() {
      return taxi_in;
    }

    /**
      * Sets the value of the 'taxi_in' field.
      * @param value The value of 'taxi_in'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setTaxiIn(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.taxi_in = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'taxi_in' field has been set.
      * @return True if the 'taxi_in' field has been set, false otherwise.
      */
    public boolean hasTaxiIn() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'taxi_in' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearTaxiIn() {
      taxi_in = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'taxi_out' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaxiOut() {
      return taxi_out;
    }

    /**
      * Sets the value of the 'taxi_out' field.
      * @param value The value of 'taxi_out'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setTaxiOut(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.taxi_out = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'taxi_out' field has been set.
      * @return True if the 'taxi_out' field has been set, false otherwise.
      */
    public boolean hasTaxiOut() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'taxi_out' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearTaxiOut() {
      taxi_out = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'cancelled' field.
      * @return The value.
      */
    public java.lang.Integer getCancelled() {
      return cancelled;
    }

    /**
      * Sets the value of the 'cancelled' field.
      * @param value The value of 'cancelled'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCancelled(java.lang.Integer value) {
      validate(fields()[21], value);
      this.cancelled = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'cancelled' field has been set.
      * @return True if the 'cancelled' field has been set, false otherwise.
      */
    public boolean hasCancelled() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'cancelled' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCancelled() {
      cancelled = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'cancellation_code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCancellationCode() {
      return cancellation_code;
    }

    /**
      * Sets the value of the 'cancellation_code' field.
      * @param value The value of 'cancellation_code'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCancellationCode(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.cancellation_code = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'cancellation_code' field has been set.
      * @return True if the 'cancellation_code' field has been set, false otherwise.
      */
    public boolean hasCancellationCode() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'cancellation_code' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCancellationCode() {
      cancellation_code = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'diverted' field.
      * @return The value.
      */
    public java.lang.Integer getDiverted() {
      return diverted;
    }

    /**
      * Sets the value of the 'diverted' field.
      * @param value The value of 'diverted'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setDiverted(java.lang.Integer value) {
      validate(fields()[23], value);
      this.diverted = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'diverted' field has been set.
      * @return True if the 'diverted' field has been set, false otherwise.
      */
    public boolean hasDiverted() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'diverted' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearDiverted() {
      diverted = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'carrier_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getCarrierDelay() {
      return carrier_delay;
    }

    /**
      * Sets the value of the 'carrier_delay' field.
      * @param value The value of 'carrier_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setCarrierDelay(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.carrier_delay = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'carrier_delay' field has been set.
      * @return True if the 'carrier_delay' field has been set, false otherwise.
      */
    public boolean hasCarrierDelay() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'carrier_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearCarrierDelay() {
      carrier_delay = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'weather_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeatherDelay() {
      return weather_delay;
    }

    /**
      * Sets the value of the 'weather_delay' field.
      * @param value The value of 'weather_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setWeatherDelay(java.lang.CharSequence value) {
      validate(fields()[25], value);
      this.weather_delay = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'weather_delay' field has been set.
      * @return True if the 'weather_delay' field has been set, false otherwise.
      */
    public boolean hasWeatherDelay() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'weather_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearWeatherDelay() {
      weather_delay = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'nas_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getNasDelay() {
      return nas_delay;
    }

    /**
      * Sets the value of the 'nas_delay' field.
      * @param value The value of 'nas_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setNasDelay(java.lang.CharSequence value) {
      validate(fields()[26], value);
      this.nas_delay = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'nas_delay' field has been set.
      * @return True if the 'nas_delay' field has been set, false otherwise.
      */
    public boolean hasNasDelay() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'nas_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearNasDelay() {
      nas_delay = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
      * Gets the value of the 'security_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getSecurityDelay() {
      return security_delay;
    }

    /**
      * Sets the value of the 'security_delay' field.
      * @param value The value of 'security_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setSecurityDelay(java.lang.CharSequence value) {
      validate(fields()[27], value);
      this.security_delay = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
      * Checks whether the 'security_delay' field has been set.
      * @return True if the 'security_delay' field has been set, false otherwise.
      */
    public boolean hasSecurityDelay() {
      return fieldSetFlags()[27];
    }


    /**
      * Clears the value of the 'security_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearSecurityDelay() {
      security_delay = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    /**
      * Gets the value of the 'late_aircraft_delay' field.
      * @return The value.
      */
    public java.lang.CharSequence getLateAircraftDelay() {
      return late_aircraft_delay;
    }

    /**
      * Sets the value of the 'late_aircraft_delay' field.
      * @param value The value of 'late_aircraft_delay'.
      * @return This builder.
      */
    public schema.dto.Flight.Builder setLateAircraftDelay(java.lang.CharSequence value) {
      validate(fields()[28], value);
      this.late_aircraft_delay = value;
      fieldSetFlags()[28] = true;
      return this;
    }

    /**
      * Checks whether the 'late_aircraft_delay' field has been set.
      * @return True if the 'late_aircraft_delay' field has been set, false otherwise.
      */
    public boolean hasLateAircraftDelay() {
      return fieldSetFlags()[28];
    }


    /**
      * Clears the value of the 'late_aircraft_delay' field.
      * @return This builder.
      */
    public schema.dto.Flight.Builder clearLateAircraftDelay() {
      late_aircraft_delay = null;
      fieldSetFlags()[28] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Flight build() {
      try {
        Flight record = new Flight();
        record.year = fieldSetFlags()[0] ? this.year : (java.lang.Integer) defaultValue(fields()[0]);
        record.month = fieldSetFlags()[1] ? this.month : (java.lang.Integer) defaultValue(fields()[1]);
        record.day_of_month = fieldSetFlags()[2] ? this.day_of_month : (java.lang.Integer) defaultValue(fields()[2]);
        record.day_of_week = fieldSetFlags()[3] ? this.day_of_week : (java.lang.Integer) defaultValue(fields()[3]);
        record.dep_time = fieldSetFlags()[4] ? this.dep_time : (java.lang.Integer) defaultValue(fields()[4]);
        record.crs_dep_time = fieldSetFlags()[5] ? this.crs_dep_time : (java.lang.Integer) defaultValue(fields()[5]);
        record.arr_time = fieldSetFlags()[6] ? this.arr_time : (java.lang.Integer) defaultValue(fields()[6]);
        record.cs_arr_time = fieldSetFlags()[7] ? this.cs_arr_time : (java.lang.Integer) defaultValue(fields()[7]);
        record.unique_carrier = fieldSetFlags()[8] ? this.unique_carrier : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.flight_num = fieldSetFlags()[9] ? this.flight_num : (java.lang.Integer) defaultValue(fields()[9]);
        record.tail_num = fieldSetFlags()[10] ? this.tail_num : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.actual_elapsed_time = fieldSetFlags()[11] ? this.actual_elapsed_time : (java.lang.Integer) defaultValue(fields()[11]);
        record.crs_elapsed_time = fieldSetFlags()[12] ? this.crs_elapsed_time : (java.lang.Integer) defaultValue(fields()[12]);
        record.air_time = fieldSetFlags()[13] ? this.air_time : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.arr_delay = fieldSetFlags()[14] ? this.arr_delay : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.dep_delay = fieldSetFlags()[15] ? this.dep_delay : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.origin = fieldSetFlags()[16] ? this.origin : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.dest = fieldSetFlags()[17] ? this.dest : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.distance = fieldSetFlags()[18] ? this.distance : (java.lang.Integer) defaultValue(fields()[18]);
        record.taxi_in = fieldSetFlags()[19] ? this.taxi_in : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.taxi_out = fieldSetFlags()[20] ? this.taxi_out : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.cancelled = fieldSetFlags()[21] ? this.cancelled : (java.lang.Integer) defaultValue(fields()[21]);
        record.cancellation_code = fieldSetFlags()[22] ? this.cancellation_code : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.diverted = fieldSetFlags()[23] ? this.diverted : (java.lang.Integer) defaultValue(fields()[23]);
        record.carrier_delay = fieldSetFlags()[24] ? this.carrier_delay : (java.lang.CharSequence) defaultValue(fields()[24]);
        record.weather_delay = fieldSetFlags()[25] ? this.weather_delay : (java.lang.CharSequence) defaultValue(fields()[25]);
        record.nas_delay = fieldSetFlags()[26] ? this.nas_delay : (java.lang.CharSequence) defaultValue(fields()[26]);
        record.security_delay = fieldSetFlags()[27] ? this.security_delay : (java.lang.CharSequence) defaultValue(fields()[27]);
        record.late_aircraft_delay = fieldSetFlags()[28] ? this.late_aircraft_delay : (java.lang.CharSequence) defaultValue(fields()[28]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Flight>
    WRITER$ = (org.apache.avro.io.DatumWriter<Flight>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Flight>
    READER$ = (org.apache.avro.io.DatumReader<Flight>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
