/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schema.dto;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum MyEnum {
  SYM1, SYM2, SYM3  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"MyEnum\",\"namespace\":\"schema.dto\",\"symbols\":[\"SYM1\",\"SYM2\",\"SYM3\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
